"""enforce one active portal session per user

Revision ID: 0677fd22deba
Revises: 58aac721ff88
Create Date: 2026-09-01 12:25:09.788829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0677fd22deba'
down_revision: Union[str, None] = '58aac721ff88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_portal_sessions_one_active_per_user', 'portal_sessions', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_portal_sessions_one_active_per_user', table_name='portal_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###
