"""add source record id

Revision ID: 1d2c5d4772e2
Revises: 6babda5797c7
Create Date: 2026-08-05 12:33:08.884746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2c5d4772e2'
down_revision: Union[str, None] = '6babda5797c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('source_record_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'weather_observations', ['source_record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_observations', type_='unique')
    op.drop_column('weather_observations', 'source_record_id')
    # ### end Alembic commands ###
