"""add weather event uniqueness constraints

Revision ID: 420c59f33ff7
Revises: 958f8fd62182
Create Date: 2026-09-01 08:47:30.165884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420c59f33ff7'
down_revision: Union[str, None] = '958f8fd62182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_weather_events_district_type_start', 'weather_events', ['district', 'weather_type', 'start_time'])
    op.create_unique_constraint('uq_weather_observation_events_observation_event', 'weather_observation_events', ['observation_id', 'weather_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weather_observation_events_observation_event', 'weather_observation_events', type_='unique')
    op.drop_constraint('uq_weather_events_district_type_start', 'weather_events', type_='unique')
    # ### end Alembic commands ###
