"""Add reporter name and mobile

Revision ID: 584baa24252b
Revises: dc8d93603fd8
Create Date: 2026-08-16 16:09:26.944346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584baa24252b'
down_revision: Union[str, None] = 'dc8d93603fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('reporter_name', sa.String(length=200), nullable=True))
    op.add_column('weather_observations', sa.Column('reporter_mobile', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_weather_observations_reporter_mobile'), 'weather_observations', ['reporter_mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_reporter_mobile'), table_name='weather_observations')
    op.drop_column('weather_observations', 'reporter_mobile')
    op.drop_column('weather_observations', 'reporter_name')
    # ### end Alembic commands ###
