"""add portal authentication tables

Revision ID: 58aac721ff88
Revises: 420c59f33ff7
Create Date: 2026-09-01 09:40:00.240283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58aac721ff88'
down_revision: Union[str, None] = '420c59f33ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('contact_no', sa.String(length=30), nullable=False),
    sa.Column('office', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'USER')", name='ck_portal_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_portal_users_email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('portal_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_portal_sessions_revoked_at'), 'portal_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_portal_sessions_token_hash'), 'portal_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_portal_sessions_user_id'), 'portal_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_sessions_user_id'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_token_hash'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_revoked_at'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    op.drop_table('portal_users')
    # ### end Alembic commands ###
