"""Add normalized geography and weather code

Revision ID: db6b2d51b987
Revises: 584baa24252b
Create Date: 2026-08-24 00:58:35.649589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6b2d51b987'
down_revision: Union[str, None] = '584baa24252b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('normalized_state', sa.String(length=100), nullable=True))
    op.add_column('weather_observations', sa.Column('normalized_district', sa.String(length=100), nullable=True))
    op.add_column('weather_observations', sa.Column('weather_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_weather_observations_normalized_district'), 'weather_observations', ['normalized_district'], unique=False)
    op.create_index(op.f('ix_weather_observations_normalized_state'), 'weather_observations', ['normalized_state'], unique=False)
    op.create_index(op.f('ix_weather_observations_weather_code'), 'weather_observations', ['weather_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_weather_code'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_normalized_state'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_normalized_district'), table_name='weather_observations')
    op.drop_column('weather_observations', 'weather_code')
    op.drop_column('weather_observations', 'normalized_district')
    op.drop_column('weather_observations', 'normalized_state')
    # ### end Alembic commands ###
